# Generated by Django 3.1.4 on 2021-04-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20210421_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userpartition',
            name='password',
        ),
    ]
